# Generated by Django 2.1.7 on 2019-04-23 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190423_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 18, 54, 29, 421937, tzinfo=utc)),
        ),
    ]
